### ISSUE TITLE
[Request] fcnvgg

### ISSUE THREAD

**Issue by naoto0804** [mil-tokyo/MCD_DA#3]
I founded that there is no `vgg_fcn` file which is defined in `models/model_util.py`.
I would really appreciate it if you could share the network for FCN8s, since I'm not really sure about how to split the base FCN8s network into `SegBase` and `SegPixelClassifier`.
Thank you in advance.

**Comment by dongzhuoyao** [comment]
as supplementary information noticed:

> We used the last convolution networks as classifier networks. All of lower layers are used as a generator.

**Comment by ksaito-ut** [comment]
Sorry for late reply. I added a network structure for vgg. vgg_fcn.py
