### ISSUE TITLE
learning rate in segmentation

### ISSUE THREAD

**Issue by dongzhuoyao** [mil-tokyo/MCD_DA#4]
it seems that when I use lr=1e-3, the validation mIoU is very low,such as 4%.

Any suggestions?

**Comment by Lufei-github** [comment]
不好意思，稍有打扰。问你个问题！
跑代码时，显示:
Downloading: "https://tigress-web.princeton.edu/~fy/drn/models/drn_d_105-12b40979.pth" to /home/zgm/.cache/torch/checkpoints/drn_d_105-12b40979.pth
但是始终下载不下来，因为看你有问问题，你应该有跑过这个代码，那你的/home/donzhuoyao/.cache/torch/checkpoints目录下肯定有drn_d_105-12b40979.pth 文件，能麻烦你把 drn_d_105-12b40979.pth 这个文件发给我吗？

**Comment by Lufei-github** [comment]
我的qq: 1323568545
或者我加你，你的qq?

**Comment by Lufei-github** [comment]
please
